name: Build & Upload Launcher

on:
  push:
    branches: [ "main", "next" ]
    paths: [ "src/**" ]

  pull_request:
    branches: [ "main", "next" ]
    paths: [ "src/**" ]

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:   
  build_and_upload:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:devel
      env:
        DEBIAN_FRONTEND: noninteractive

    steps:
    - name: Install Deps
      run: |
        apt update
        apt install -y libgtk-4-1 libgtk-4-dev libadwaita-1-0 libadwaita-1-dev git curl openssl libssl-dev

    - uses: dtolnay/rust-toolchain@stable

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build
      run: cargo build --release --verbose

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Launcher
        path: target/release/honkers-launcher
